<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empresa [
    <!ELEMENT empresa (empleado+)>
    <!ELEMENT empleado (nombre, id, cargo, salario)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT cargo (#PCDATA)>
    <!ELEMENT salario (#PCDATA)>
]>

<empresa>
    <empleado>
        <nombre>Daniel</nombre>
        <id>69</id>
        <cargo>Gerente</cargo>
        <salario>5000â‚¬</salario>
    </empleado>
</empresa>
