<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE company [
    <!ELEMENT company (employee+)>
    <!ELEMENT employee (name, id, position, salary)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT position (#PCDATA)>
    <!ELEMENT salary (#PCDATA)>
]>

<company>
    <employee>
        <name>Daniel</name>
        <id>69</id>
        <position>Gerente</position>
        <salary>5000â‚¬</salary>
    </employee>
</company>
